# Generated by Django 4.2.1 on 2023-06-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="rank",
            field=models.CharField(
                choices=[
                    ("diamond", "다이아몬드"),
                    ("gold", "골드"),
                    ("silver", "실버"),
                    ("bronze", "브론즈"),
                ],
                default="bronze",
                max_length=25,
            ),
        ),
    ]
