# Generated by Django 4.2.1 on 2023-06-16 01:54

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_board_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=django_bleach.models.BleachField(),
        ),
        migrations.AlterField(
            model_name="post", name="content", field=django_bleach.models.BleachField(),
        ),
    ]
