name: Django CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    if: ${{ github.event_name == 'push'}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install system level dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev libdbus-1-dev libsystemd-dev libcairo2-dev libjpeg-dev libgif-dev pkg-config build-essential libpq-dev libvirt-dev

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply database migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test
